# -*- coding: utf-8 -*-
"""QuerySearch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-R7g5EBwiDQwK5P0fuPLbR-V38_aBgxg
"""

'''The code below doesn't function properly due to UnvoundLocalError,
However the second code represents more simplified but functioning piece of code.'''

#Attempt 1 --> Loop with index & rename[Doesn't function properly]
'''i = 0
def search_function(query, data_list):
  for index in data_list:
    if query in data_list:
      i += 1
    else:
      data_list[i] = 'UNASSIGNED'
    return -1

result = search_function('S_', ['S_',2,3,4])
print(result)'''

#Attempt 2 --> Return Values from search function[Functions Properly]
def new_Function(search, new_List):
  if search in new_List:
    return 1
  else:
    return 0

new_Result = new_Function('S_', ['S_',2,3,4])
print(new_Result)